[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "appstats.nantesmetropolefutsal.fr"

[theme]
primaryColor = "#C09D5A"
backgroundColor = "#1D2945" 
secondaryBackgroundColor = "#2A3B5A"
textColor = "#FFFFFF"
